### ISSUE TITLE
LiveAuthClient.ExchangeAuthCodeAsync doesn't seem to handle errors properly

### ISSUE THREAD

**Issue by paya-cz** [liveservices/LiveSDK-for-Windows#27]
In the `Microsoft.Live.Desktop.Samples.ApiExplorer`, when I modify `MainForm.OnAuthCompleted` line
```c#
LiveConnectSession session = await this.AuthClient.ExchangeAuthCodeAsync(result.AuthorizeCode);
```
to
```C#
// Use garbage code to test error handling
LiveConnectSession session = await this.AuthClient.ExchangeAuthCodeAsync("j93r0293kr0293kr");
```
The line after `await` never executes. If I rewrite the line to:
```C#
LiveConnectSession session = this.AuthClient.ExchangeAuthCodeAsync("j93r0293kr0293kr").Result;
```
the code throws a `TargetInvocationException` in `Program.cs` on the line:
```C#
Application.Run(new MainForm());
```

**Comment by peternied** [comment]
@paya-cz debugging on my local machine, I get an authorization code that looks like #######-####-####-####-############, also the code seems to be encoded as hex which looks very different from what you are showing in your example.  Where did you get your authorization code from?

If you are still having trouble figuring out what is going on, could you get a fiddler trace of the sample application running as this will allow me to quickly diagnose the problem.

**Comment by paya-cz** [comment]
@peternied as mentioned in the comment line just above the code, the authorization code is just a garbage that I put in myself. Whole purpose of that was to see how the library handles errors - in this case, how it would handle garbage auth code. Getting a standard exception would be so much preferred rather than a deadlock or exception in `Application.Run`. The code for handling this type of problems is already there, it just seems to not be implemented properly. In `LiveAuthClientCore.cs`, it properly executes `this.codeExchangeTask.SetException(authResult.Error);` in `OnExchangeCodeCompleted` event handler (it sets `LiveAuthException` in the `SetException`), but for a reason that's beyond me, it fails and makes either a deadlock or `TargetInvocationException`.

**Comment by peternied** [comment]
Analyzing how the program works with a bad login code, we should execute a request that returns an error inside of LiveLoginResult via the LiveAuthRequestUtility's RequestAccessToken method.   Inside of LiveAuthClientCore, the continuation is called, which in turn causes the OnExchangeCodeCompleted function to be called, setting the exception on the task instead of the result.  Now that we are back on MainForm.cs inside of OnAuthCompleted, we should get the exception at the resolution of the await result, which then triggers the exception to be logged to the ApiExplorer output window.  (This is at least what I'm seeing).

Now if you change the await into a .Result, you are now resolving the task on the main thread of the application which causes a slightly different exception to be thrown, specifically TargetInvocationException.  But if you look into the inner aggregate exception you'll find the same Microsoft.Live.LiveAuthException that would normally have been caught by the try block that call is inside of.  You can verify this behavior for yourself by adding catch (Exception e) {this.LogOutput(e.ToString());} at the bottom of that method.  I've pushed this branch which contains this change https://github.com/peternied/LiveSDK-for-Windows/tree/BadAuthToken 

As far as I can tell by the application design, you should get an error in that output window, and it should help you understand what is going wrong, and I can't find a deadlock or blocking issue that would prevent the application from working.

**Comment by peternied** [comment]
Hmm, not sure what is wrong there, as I don't seem to be able to repro your issue, if you could put up a repro on your personal fork I can give it a quick look.

**Comment by paya-cz** [comment]
Please take a look here https://github.com/paya-cz/LiveSDK-for-Windows/tree/exceptions

You will need your own refresh token for the 0000000048122D4E app. Be sure to disconnect from internet when you run the app.

**Comment by peternied** [comment]
Thanks! FYI -  I'll take a look into this tomorrow.

**Comment by peternied** [comment]
Could you take a quick look and see if this resolves your problem?  Btw thanks for the repro that helped a bunch narrow this issue down!

**Comment by paya-cz** [comment]
Thanks, it seems your commit fixed the issue. At least I haven't been able to find a way to break it again. :-) Cheers from Czech Republic!
