### ISSUE TITLE
download / upload windows phone 8.1

### ISSUE THREAD

**Issue by MannusEtten** [liveservices/LiveSDK-for-Windows#35]
I try to use the Live SDK to upload a file to OneDrive.
All the methods I tried on the Windows Phone result in "this method is not implemented"

and the examples on the internet mainly describe "UploadAsync"  but this method is gone in the latest version of the SDK

**Comment by peternied** [comment]
MannusEtten looking inside of the WP8 directory of this sdk, specifically in the CoreConcepts sample application, there is an example of using [UploadAsync](https://github.com/liveservices/LiveSDK-for-Windows/blob/e0eea68cfa1d4aebc3bd2e4b907ba2d128200360/src/WP8/Samples/CoreConcepts/Upload.xaml.cs#L123)

If you work with that example project does that resolve your issue?

**Comment by MannusEtten** [comment]
no because the uploadAsync-method is not available in the Live SDK 5.6, that is removed from the 5.5 release...

I start to build a new app so I want to work with also the latest stable releases of dependencies. 

So I start to doubt if somebody used the SDK 5.6 together with universal apps or windows phone 8.1

**Comment by peternied** [comment]
"no because the uploadAsync-method is not available in the Live SDK 5.6"  I don't understand how to interpret this statement, are you saying that when you use reference binaries (From the LiveSDK.msi on MSDN) that you are unable to compile that against that method?  Are you saying this is a runtime exception when you attempt to user the application?

Could you try cloning this repository and building the binaries directly, and if you run into trouble to include the full call stack/message of the error?

**Comment by MannusEtten** [comment]
i have found the issue yesterday and in the end, i figured out it had nothing to do with the Live SDK. the synchronisation with OneDrive works like a charm now :-)
