### ISSUE TITLE
Live SDK package on Nuget doesn't work in Universal app and has to be installed manually

### ISSUE THREAD

**Issue by mcintyre321** [liveservices/LiveSDK-for-Windows#58]
see this SO question: http://stackoverflow.com/questions/31855258/universal-windows-plateform-and-live-sdk

**Comment by eloekset** [comment]
+1 This should just work now that Windows 10 and VS2015 are RTM. Is an update to the NuGet package all that needs to be done?

**Comment by rgregg** [comment]
We aren't planning on updating the Live SDK for WIndows 10 / universal app support. We're delivering new SDKs for the various services that were covered by the Live SDK:
* Mail/Calendar/Contacts: https://dev.outlook.com/
* Files/OneDrive: https://dev.onedrive.com/

**Comment by mcintyre321** [comment]
OneNote?

**Comment by zoint** [comment]
What if we were just using it purely for OAuth / single sign in purposes with Azure Mobile Services. What route should take for this?

**Comment by markemalek** [comment]
I have the same question as Zoint. 
I have a UWP application that is currently using LiveSDK to authenticate a Windows account to access an Azure Mobile Service. 
I am using v5.6.3. It is working, but the first time running the app for the day takes in 20-30+ seconds to authenticate, consequent calls are not as painful at 5-8 seconds. Users are complaining about the slowness. 

What is the new correct SDK to authenticate to an Azure Mobile Service? 

Example code-

```
    public LiveConnectSession session;
    public async System.Threading.Tasks.Task Authenticate()
    {
        LiveAuthClient liveIdClient = new LiveAuthClient("https://-------.azure-mobile.net/"); //removed mobile service name
        while (session == null)
        {
            LiveLoginResult result = null;
            try
            {
                result = await liveIdClient.InitializeAsync(new string[] { "wl.signin", "wl.basic", "wl.offline_access" });

                if (result != null)
                {
                    if (result.Status != LiveConnectSessionStatus.Connected)
                    {
                        result = await liveIdClient.LoginAsync(new string[] { "wl.signin", "wl.basic", "wl.offline_access" });
```

I have also started using **wl.emails** instead of **wl.basic**.

Thank you!
